### ISSUE TITLE
Hiding the SSID of the esp8266 once it has been setup

### ISSUE THREAD

**Issue by gilshahar7** [denis-stepanov/esp8266-yeelight-switch#16]
Hey, thanks for this project, im using it everyday.

I was wondering if its possible to hide the "ybutton1" SSID from broadcasting. 
I had already set it up and i dont want the esp to keep broadcasting the SSID.
maybe it will be possible to access the interface from the lan by using the local ip of the esp instead.

**Comment by denis-stepanov** [comment]
Thanks for the report. Yes, indeed, it is a side effect because ESP remembers its previous Wi-Fi state. I will fix it.

**Comment by denis-stepanov** [comment]
I could not reproduce this locally using ESP Core 2.5.2, but I had seen this effect on some other project of mine, so I have just copied the fix from there. Hoping it will work.
